# Generated by Django 5.0.4 on 2024-04-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_initial'),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='foods',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='cafe.foods'),
        ),
    ]
