# Generated by Django 5.0.4 on 2024-04-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_initial'),
        ('order', '0003_remove_order_foods_delete_orderitem_order_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='all_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='foods',
        ),
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cafe.foods'),
        ),
    ]
