# Generated by Django 5.0.4 on 2024-04-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_quantity_order_all_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='all_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
